routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [
  'uses' => 'userController@verifyOtp',
])->name('main');
Route::middleware('authuser')->group(function()
{
    Route::get('/myprofile', 'userController@myprofile');
    Route::get('/myhistory', 'userController@myhistory');
    Route::get('/auto-recharge', 'userController@autoRecharge');
    Route::post('/auto-recharge-store', 'userController@autoRechargeStore');
    Route::get('/show-pre-recharge', 'userController@showPreAutoRecharge');
    Route::get('/myprofile/wallet', 'userController@wallet');
    Route::post('/walletrecharge', 'HomeController@walletrecharge');
    Route::post('/mobilerecharge', 'HomeController@mobilerecharge');
    Route::post('/mobilerechargemiddle', 'HomeController@mobilerechargemiddle');
    Route::post('/electrictmiddle', 'HomeController@electricityBilling');

    
        Route::get('/bbps/search-biller', 'Bbps\SearchBiller@index');
        Route::get('/bbps/fetch-biller', 'Bbps\FetchBiller@index');
        Route::get('/bbps/pay-bill', 'Bbps\PayBill@index');
        Route::get('/bbps/process-pay', 'Bbps\ProcessPay@index');
    

});

Route::post('/walletrechargeresponse', '\App\Classes\Wallet@gateway_Response_Handler_wallet');
Route::match(['get','post'],'/walletrechargeresponse', '\App\Classes\Wallet@gateway_Response_Handler_wallet');
Route::match(['get','post'],'/mobilerechargeresponse', '\App\Classes\Wallet@gateway_Response_Handler_mobile');

// Route::get('/operators', '\App\Classes\Wallet@operators_test');
Route::get('/pay-status', 'userController@refreshTransactionStatus');
// Route::get('/pay-status', function()
// {
//     Artisan::call('UpdateTransactionStatus:check');
// });

Route::get('/clear-cache', function()
{
    Artisan::call('cache:clear');
    Artisan::call('config:cache');
    Artisan::call('config:clear');
    Artisan::call('view:clear');

    return "Cleared!";
});
Route::get('/clear-view', function()
{
    Artisan::call('cache:clear');
    Artisan::call('view:clear');

    return "Cleared!";
});

Route::get('/no-verified/{id}', 'userController@noVerified');

Auth::routes();


Route::post('/loginAction', 'TrackController@loginAction')->name('loginAction');
Route::post('/registerAction', 'TrackController@registerAction')->name('registerAction');
Route::get('/userAccountActivation/{token}', 'TrackController@userAccountActivation')->name('userAccountActivation');

Route::get('/test', function()
{
    return view('test');
});

Route::get('verifyOtp', [
  'uses' => 'userController@verifyOtp',
]);

Route::get('sendOtp', [
  'uses' => 'userController@sendCode',
]);
Route::get('resetOtp', [
  'uses' => 'userController@resetOtp',
]);
Route::get('sdxxxafbbfsascasd1aa', [
  'uses' => 'userController@resetAll',
]);

Route::post('/reset-password', 'Auth\ResetPasswordController@customReset')->name('reset-password');

Route::get('/index', function()
{
    return view('index');
});

Route::get('/composer-install', function()
{
    $output = shell_exec('cd .. && composer update');

    return $output;
});
Route::get('/composer-dumpautoload', function()
{
    $output = shell_exec('composer dumpautoload');

    return $output;
});
Route::get('/artisan-config-cache', function()
{
    Artisan::call('config:cache');
});

Route::get('mantis/authentication', 'MantisController@authentication');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/feedback', 'HomeController@feedback')->name('feedback');
Route::any('/feedback-post', 'HomeController@feedbackPost')->name('feedback_post');

Route::post('recharge', 'HomeController@rechargeMobile')->middleware('web');
Route::get('/ccavform', 'HomeController@ccavform');
Route::get('/ccavredirect', 'HomeController@ccavRequestHandler');
Route::group(['prefix' => 'frontend', 'as' => 'frontend.'], function()
{

    Route::get('/', 'TrackController@index');

    Route::get('/aboutus', 'HomeController@aboutus');

    Route::get('/faq', 'HomeController@faq')->name('faq');

    Route::get('/bus', 'HomeController@bus');

    Route::get('/support', 'HomeController@support')->name('support');
    Route::any('/support-post', 'HomeController@supportPost')->name('support_post');

    Route::get('/sitemap', 'HomeController@sitemap');

    Route::get('/terms', 'HomeController@terms');

    Route::get('/privacy-policy', 'HomeController@privacyPpolicy')->name('privacy_policy');
    Route::get('/refund-policy', 'HomeController@refundPolicy')->name('refund_policy');

    Route::get('/contact', 'HomeController@contact');

    Route::post('/updateTrack', 'TrackController@updateTrack');

    Route::get('/login', 'TrackController@login');

    Route::post('/login_check', 'TrackController@login_check');

    Route::get('/logout', 'TrackController@logout');

});

Route::auth();

//Route::get('/admin', 'AdminController@test')->middleware('auth');
Route::get('/user', 'AdminController@userShow');
Route::get('/auto-recharge-corn', 'AutoRechargeController@autoRechargeCorn');
Route::get('/auto-recharge-show', 'AdminController@autoRechargeShow');
Route::get('/coupon', 'CouponController@index');
Route::get('/coupon/create', 'CouponController@create');
Route::post('/coupon', 'CouponController@store');
Route::get('/coupon/discount-type', 'CouponController@discountType');
Route::get('/coupon/cash-back-type', 'CouponController@cashBackType');
Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout')->name('logout');
Route::prefix('admin')->group(function() {
    Route::prefix('auth')->group(function() {
        Route::get('/login', 'Admin\AuthController@login')->name('admin.login');
        Route::get('/logout', 'Admin\AuthController@logout')->name('admin.logout');
        Route::get('/passwordReset', 'Admin\AuthController@passwordReset')->name('admin.reset');
        Route::post('/doReset', 'Admin\AuthController@doReset')->name('admin.reset.action');
        Route::get('/passwordRecover/{token}', 'Admin\AuthController@passwordRecover')->name('admin.passwordRecover');
        Route::post('/doRecover/{token}', 'Admin\AuthController@doRecover')->name('admin.recover.action');
        Route::post('/loginAction', 'Admin\AuthController@doLogin')->name('admin.login.action');
    });
    Route::middleware(['admin'])->group(function(){
        Route::get('/', 'Admin\AdminsController@dashboard')->name('admin.dashboard');
        Route::get('/dashboard', 'Admin\AdminsController@dashboard')->name('admin.dashboard');
          Route::middleware(['admin'])->group(function(){
        Route::get('/', 'Admin\AdminsController@dashboard')->name('admin.dashboard');
        Route::get('/dashboard', 'Admin\AdminsController@dashboard')->name('admin.dashboard');
        
        Route::get('/transactions', 'Admin\AdminsController@transactions')->name('admin.transactions');

        Route::prefix('users')->group(function() {
            Route::get('/', 'Admin\UsersController@index')->name('admin.users');
              Route::get('/expenditures', 'Admin\UsersController@expenditures')->name('admin.users.expenditures');
            Route::get('/{id}/cashBack', 'Admin\UsersController@cashback')->name('admin.user.cashback');
            Route::post('/submitCashBack/{id}', 'Admin\UsersController@updateCashBack')->name('admin.user.cashback.submit');
            Route::get('/{id}/suspend', 'Admin\UsersController@suspend')->name('admin.user.suspend');
            Route::get('/{id}/activate', 'Admin\UsersController@activate')->name('admin.user.activate');
            Route::get('/{id}/delete', 'Admin\UsersController@delete')->name('admin.user.delete');
            Route::get('/{id}/transactions', 'Admin\UsersController@transactions')->name('admin.user.transactions');
        });
        Route::prefix('transactions')->group(function() {
            Route::get('/walletTransactions', 'Admin\AdminsController@walletTransactions')->name('admin.walletTransactions');
            Route::get('/dthTransactions', 'Admin\AdminsController@dthTransactions')->name('admin.dhtTransactions');
            Route::get('/mobileTransactions', 'Admin\AdminsController@mobileTransactions')->name('admin.mobileTransactions');
            Route::get('/postPaidTransactions', 'Admin\AdminsController@postPaidTransactions')->name('admin.postPaidTransactions');
        });

    });

    });
});

resources/views/frontend/about.blade.php
@extends('blades.base')



{{-- @section('page title', 'Index') --}}

@section('css')
<link rel="stylesheet" href="{{ asset('css/custom.css')}}">
@endsection

@section('innerbanner')

<!-- innerbanner -->    

<div class="banner">
	<s-banner></s-banner>
</div>

<!-- //innerbanner -->

@endsection



@section('breadcrumbs')

@endsection



@section('horizontal tab')



@endsection



@section('vertical tab')





	<div class="w3layouts-breadcrumbs text-center">

		<div class="container">

			<span class="agile-breadcrumbs"><a href="/"><i class="fa fa-home home_1"></i></a> / <span>About</span></span>

		</div>

	</div>

	<!-- //breadcrumbs -->



	<!-- About-page -->

	   <div class="terms w3ls-about w3layouts-content">

		<div class="container">

			<h3 class="w3-head">About Us</h3>
			<h6>What is Zapwallet?</h6>

			<b>Quick & Fast:</b>
			<p>The term Zap means “Quick”.</p>
			<p>We tend to provide quickest recharges in just under 3 Clicks.</p>

			<b>Auto-Recharge:</b>
			<p>Zapwallet also tries to provide auto recharge to your prepaid mobile using the Auto Recharge system.</p>

			<b>Bus Tickets:</b>
			<p>Zapwallet provides Bus Tickets for 146000+ Routes and 2000+ Bus Operators.</p>

			<b>Shopkeeper Earnings:</b>
			<p>Zapwallet assures monthly earnings of around Rs.500/- to Rs.50000/- to each and every Shopkeepers who do cross the maximum amount of transactions.</p>

			<h6>Why Use Zapwallet?</h6>
			<ol start="1">
				<li>We recommend each and everyone to use zapwallet for its quickness. Recharge done in just 2 clicks.</li>
				<li>If case of any unnecessary deduction of money, refund is made within 3 – 21 working days.</li>
				<li>Quickest customer support. The First Company to provide whatsapp support.</li>
			</ol>
			<h6>We Promise:</h6>
			<ol start="1">
				<li>Good Customer Support.</li>
				<li>Quickest Service.</li>
				<li>Assured Earnings to all Shopkeepers.</li>
				<li>Discounts and Cashbacks on all Recharge and Bus tickets you book using your debit card or zapwallet.</li>
			</ol>




	</div>

</div>

    <!--//About-page-->











			<!-- start-smoth-scrolling -->

		<!-- //here ends scrolling icon -->

@endsection



@section('tab title')

    Plan

@endsection

resources/views/frontend/bus.blade.php
@extends('blades.base')

{{-- @section('page title', 'Index') --}}

@section('innerbanner')
<!-- innerbanner -->    
<div class="agileits-inner-banner">
        
    </div>
<!-- //innerbanner -->
@endsection

@section('breadcrumbs')
@endsection

@section('horizontal tab')

@endsection

@section('vertical tab')


<!-- breadcrumbs -->
	<div class="w3layouts-breadcrumbs text-center">
		<div class="container">
			<span class="agile-breadcrumbs"><a href="/"><i class="fa fa-home home_1"></i></a> / <span>Bus</span></span>
		</div>
	</div>
	<!-- //breadcrumbs -->
	<!-- Bus -->
	<div class="agile-bus w3layouts-content">
     <div class="container">
	<div class="col-md-5 bann-info1">
		<i class="train-icon fa fa-bus"></i>
	</div>
         <div class="col-md-5 bann-info">
		<h3>Search for Bus Tickets</h3>
        <div class="book-a-ticket">
							<div class=" bann-info">
								<form action="bus-list.html" method="post">
									<div class="ban-top">
										<div class="bnr-left">
											<label class="inputLabel">From:</label>
											<input class="city" type="text" placeholder="Enter a city or local area" required="required" />
										</div>
										
										<div class="bnr-left">
											<label class="inputLabel">To:</label>
											<input class="city" type="text" placeholder="Enter a city or local area" required="required" />
										</div>
											<div class="clearfix"></div>
									</div>
									 <div class="ban-bottom">
											<div class="bnr-right">
												<label class="inputLabel">Date of Journey:</label>
				<input class="date" id="datepicker" type="text" placeholder="dd-mm-yyyy"  required="required" />
											</div>
											<div class="bnr-right">
												<label class="inputLabel">Date of Return<span class="opt">&nbsp;(Optional):</span></label>
				<input class="date" id="datepicker1" type="text" placeholder="dd-mm-yyyy" />
											</div>
												<div class="clearfix"></div>
												<!-- start-date-piker -->
												<link rel="stylesheet" href="css/jquery-ui.css">
												<script src="/js/jquery-ui.js"></script>
													<script>
														$(function() {
														$( "#datepicker,#datepicker1" ).datepicker();
														});
													</script>
											<!-- /End-date-piker -->
										</div>
									<div class="search">
									     <input type="submit" class="submit" value="Search">
									
									</div>
								</form>
							</div>
					</div>

	</div>
        

	
	<div class="clearfix"></div>
	</div>
</div>
<!-- //Bus -->

<!-- subscribe -->
@endsection

@section('tab title')
    Plan
@endsection

resources/views/frontend/sitemap.blade.php
@extends('blades.base')

{{-- @section('page title', 'Index') --}}

@section('css')
<link rel="stylesheet" href="{{ asset('css/custom.css')}}">
@endsection

@section('innerbanner')

<!-- innerbanner -->    

<div class="banner">
	<s-banner></s-banner>
</div>

<!-- //innerbanner -->

@endsection

@section('breadcrumbs')
@endsection

@section('horizontal tab')

@endsection

@section('vertical tab')

<!-- breadcrumbs -->
	<div class="w3layouts-breadcrumbs text-center">
		<div class="container">
			<span class="agile-breadcrumbs"><a href="/"><i class="fa fa-home home_1"></i></a> / <span>Sitemap</span></span>
		</div>
	</div>
	<!-- //breadcrumbs -->

	<!-- Sitemap-page -->
	    <div class="icons w3layouts-content">
		<div class="container">
			<h3 class="w3-head">Sitemap</h3>
	   <!-- sitemap -->
			<div class="sitemap">
					<div class="col-md-6 sitemap-grid">
						<h4>Online mobile Rechange and Bill payment</h4>
						<ul>
							<li><a href="/#parentVerticalTab1.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Airtel</a></li>
							<li><a href="/#parentVerticalTab1.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Aircel</a></li>
							<li><a href="/#parentVerticalTab1.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Tata Docomo</a></li>
							<li><a href="/#parentVerticalTab1.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>BSNL</a></li>
							<li><a href="/#parentVerticalTab1.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Tata Docomo</a></li>
							<li><a href="/#parentVerticalTab1.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Reliance GSM</a></li>
							<li><a href="/#parentVerticalTab1.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Reliance CDMA</a></li>
							<li><a href="/#parentVerticalTab1.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Telenor</a></li>
							<li><a href="/#parentVerticalTab1.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>MTS</a></li>
							<li><a href="/#parentVerticalTab1.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Jio</a></li>
						</ul>
						<h4>Online DataCard Recharge</h4>
						<ul>
							<li><a href="career.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Tata Photon</a></li>
							<li><a href="/#parentVerticalTab3.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>MTS MBrowse</a></li>
							<li><a href="/#parentVerticalTab3.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Airtel</a></li>
							<li><a href="/#parentVerticalTab3.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Aircel</a></li>
							<li><a href="/#parentVerticalTab3.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>BSNL</a></li>
							<li><a href="/#parentVerticalTab3.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>MTNL Delhi</a></li>
							<li><a href="/#parentVerticalTab3.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Vodafone</a></li>
							<li><a href="/#parentVerticalTab3.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Idea</a></li>
							<li><a href="/#parentVerticalTab3.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>MTNL Mumbai</a></li>
							<li><a href="/#parentVerticalTab3.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Tata Photon Whiz</a></li>
						</ul>                        
		                <h4>Online DTH(TV) Recharge</h4>
						<ul>
							<li><a href="/#parentVerticalTab2.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Airtel Digital TV Recharges</a></li>
							<li><a href="/#parentVerticalTab2.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Dish TV Recharges</a></li>
				            <li><a href="/#parentVerticalTab2.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Tata Sky Recharges</a></li>
                            <li><a href="/#parentVerticalTab2.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Reliance Digital TV Recharges</a></li>
                            <li><a href="/#parentVerticalTab2.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Sun Direct Recharges</a></li>
                            <li><a href="/#parentVerticalTab2.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Videocon D2H Recharges</a></li>
						</ul>
						<h4>Electricity</h4>
						<ul>
							<li><a href="/#parentVerticalTab4.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Electricity-1</a></li>
							<li><a href="/#parentVerticalTab4.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Electricity-2</a></li>
							<li><a href="/#parentVerticalTab4.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Electricity-3</a></li>
							<li><a href="/#parentVerticalTab4.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Electricity-4</a></li>
							<li><a href="/#parentVerticalTab4.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Electricity-5</a></li>
							<li><a href="/#parentVerticalTab4.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Electricity-6</a></li>
						</ul>
					</div>
					<div class="col-md-6 sitemap-grid">
						<h4>Landline Bill Payments</h4>
						<ul>
							<li><a href="/#parentVerticalTab5.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Act</a></li>
							<li><a href="/#parentVerticalTab5.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Airtel</a></li>	<li><a href="/#parentVerticalTab5.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>BSNL</a></li>
							<li><a href="/#parentVerticalTab5.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Reliance</a></li>

						</ul>
						<h4>Broadband Bill Payments</h4>
						<ul>
							<li><a href="/#parentVerticalTab6.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Act</a></li>
							<li><a href="/#parentVerticalTab6.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Airtel</a></li>	<li><a href="/#parentVerticalTab6.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>BSNL</a></li>
						</ul>
						<h4>Gas</h4>
						<ul>
							<li><a href="/#parentVerticalTab7.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Gas-1</a></li>
							<li><a href="/#parentVerticalTab7.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Gas-2</a></li>
							<li><a href="/#parentVerticalTab7.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Gas-3</a></li>
							<li><a href="/#parentVerticalTab7.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Gas-4</a></li>
							<li><a href="/#parentVerticalTab7.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Gas-5</a></li>
						</ul>
						<h4>Metro</h4>
						<ul>
							<li><a href="/#parentVerticalTab9.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Metro</a></li>
						</ul>
						<h4>Pages</h4>
						<ul>
							<li><a href="about.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>About</a></li>
							<li><a href="support.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Support</a></li>
							<li><a href="terms.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Terms & Conditions</a></li>
							<li><a href="{{ route('frontend.faq') }}"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Faq</a></li>
							<li><a href="feedback.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Feedback</a></li>
							<li><a href="contact.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Contact</a></li>
							<li><a href="shortcodes.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Shortcodes</a></li>
							<li><a href="icons.html"><i class="fa fa-long-arrow-right" aria-hidden="true"></i>Icons Page</a></li>
                        </ul>
					</div>
					<div class="clearfix"></div>
			</div>
			<!-- /sitemap -->
		</div>
	</div>
    <!--//Sitemap-page-->


<!-- subscribe -->
@endsection

@section('tab title')
    Plan
@endsection

resources/views/frontend/support.blade.php
@extends('blades.base')

{{-- @section('page title', 'Index') --}}

@section('css')
<link rel="stylesheet" href="{{ asset('css/custom.css')}}">
@endsection

@section('innerbanner')

<!-- innerbanner -->    

<div class="banner">
	<s-banner></s-banner>
</div>

<!-- //innerbanner -->

@endsection

@section('breadcrumbs')
@endsection

@section('horizontal tab')

@endsection

@section('vertical tab')

<!-- innerbanner -->	

<!-- //innerbanner -->

<!-- breadcrumbs -->
	<div class="w3layouts-breadcrumbs text-center">
		<div class="container">
			<span class="agile-breadcrumbs"><a href="/"><i class="fa fa-home home_1"></i></a> / <span>Support</span></span>
		</div>
	</div>
	<!-- //breadcrumbs -->

	<!-- Support-page -->
	    <div class="support w3layouts-content">
		<div class="container">
			<h3 class="w3-head">Support Page</h3>
            <div class="col-md-8 w3ls-supportform">
	       <form action="{{ route('frontend.support_post') }}" method="POST" name="sentMessage" id="contactForm" novalidate>
			   {{ csrf_field() }}
                <select required name="request_type">
                      <option value="Payment">Payment</option>
                      <option value="Recharge">Recharge</option>
                      <option value="Booking">Booking</option>
                      <option value="Account">Account</option>
                      <option value="Others">Others</option>
                    </select>
					<div class="control-group form-group">
						<div class="controls">
							<input type="text" class="form-control" name="name_is" placeholder="Enter your Name" id="name" required data-validation-required-message="Please enter your name.">
						</div>
					</div>
					<div class="control-group form-group">
						<div class="controls">
							<input type="email" class="form-control" name="email" placeholder="Enter your Email ID" id="email" required data-validation-required-message="Please enter your email address.">
						</div>
					</div>
                    <div class="control-group form-group">
                        <div class="controls">
                            <input type="tel" class="form-control" name="phone" placeholder="Enter mobile Number" id="phone" required="" data-validation-required-message="Please enter your phone number." aria-invalid="false">
							<p class="help-block"></p>
						</div>
                    </div>
						<div class="control-group form-group">
							<div class="controls">
								<textarea rows="10" cols="100" class="form-control" placeholder="Please write here" id="message" name="message" required data-validation-required-message="Please enter your message" maxlength="999" style="resize:none"></textarea>
							</div>
						</div>
						<div id="success"></div>
						<!-- For success/fail messages -->
						<button type="submit" class="submit btn btn-primary">Create Ticket</button>
					<div class="clearfix"></div>	
					</form>
                </div>
            <div class="col-md-4 agileits-support">
                <ul>
                    <li><strong>Mail to:</strong> <a href="mailto:care@zapwallet.in">care@zapwallet.in</a></li>
                    <li><a class="w3-faq" href="{{ route('frontend.faq') }}">Faq</a></li>
                </ul>
            </div>
            <div class="clearfix"></div>
<!-- js files for contact from validation -->
		<script src="/js/jqBootstrapValidation.js"></script>
		<script src="/js/contact_me.js"></script>
	<!-- //js files for contact from validation -->

	</div>
</div>
    <!--//Support-page-->


<!-- subscribe -->
@endsection

@section('tab title')
    Plan
@endsection
<!-- /html -->